# Generated by Django 5.2 on 2025-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='img/default_user_image.png', null=True, upload_to='profile_image'),
        ),
    ]
