# Generated by Django 5.2 on 2025-04-19 13:25

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=300, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='app_logos/')),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apk_files/')),
                ('version', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('downloads', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_category', to='category.category')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_developer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
    ]
