# Generated by Django 5.2 on 2025-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=models.ImageField(blank=True, default='img/default_image.png', null=True, upload_to='app_logos/'),
        ),
    ]
